### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by surfaceflinger**

### CODE REVIEW

**Comment by CDFN** [comment]
I think you cleaned up my code a bit too much, thanks though :joy:

**Comment by ghost** [comment]
yikes

**Comment by kucharski-s** [comment]
Cleanup like `rm -rf /`.

**Comment by k0l0r3k99** [comment]
Works fine for me, I think we should reopen this PR and merge it

**Comment by CDFN** [comment]
😂😂😂😂😂😂

**Comment by wiv0** [comment]
actually better than the current code

**Comment by CDFN** [comment]
cringe

**Pull request closed without merging**
